version: '3.5'
services:
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        environment:
            - ENV=development
            - PORT=8000
            - DB=mongodb://mongodb:27017/yelmis
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/usr/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/usr/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
    default:
        name: app
